DROP TABLE IF EXISTS foo;
CREATE TEMP TABLE foo (a int);
INSERT INTO foo VALUES (1), (NULL), (4), (2), (NULL), (3);
SELECT * FROM foo ORDER BY a DESC NULLS LAST;
--SELECT * FROM foo ORDER BY a DESC NULLS FIRST;